version: 2
updates:
  # Enable checks for the default vendor folder
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"

  # Enable checks for Google API Client package
  - package-ecosystem: "composer"
    directory: "/lib/Google"
    schedule:
      interval: "weekly"

  # Enable checks for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
